// Carte issue du tableau de bord de navigation.
function drawMap(s){const canvas=$('#map'),c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,scale=100,ox=w/2,oy=h*.63;c.clearRect(0,0,w,h);const xy=(x,y)=>[ox+x*scale,oy-y*scale];
 c.strokeStyle='#264238';c.lineWidth=1;for(let x=ox%50;x<w;x+=50){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}for(let y=oy%50;y<h;y+=50){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}
 for(const sector of s.plan.sectors||[]){if(sector.distance_m!=null)continue;const [lx,ly]=xy(s.config.lidar_x_m,s.config.lidar_y_m);const a=sector.angle_deg*Math.PI/180-Math.PI/2;c.fillStyle='#ecac4930';c.beginPath();c.moveTo(lx,ly);c.arc(lx,ly,Math.hypot(w,h),(a-Math.PI/180),(a+Math.PI/180));c.closePath();c.fill()}
 for(const p of s.scan?.points||[]){if(!(p.distance_mm>0&&p.quality>0))continue;const a=s.config.lidar_sign*(p.angle_deg-s.config.lidar_front_deg)*Math.PI/180;const [x,y]=xy(s.config.lidar_x_m+p.distance_mm/1000*Math.sin(a),s.config.lidar_y_m+p.distance_mm/1000*Math.cos(a));c.fillStyle='#f09078';c.fillRect(x-2,y-2,4,4)}
 for(const p of s.plan.candidates||[]){c.strokeStyle=p.allowed?'#54857460':'#81918730';c.lineWidth=1;c.beginPath();c.moveTo(ox,oy);for(const [x,y]of p.path||[])c.lineTo(...xy(x,y));c.stroke()}
 if(s.plan.target){const a=s.plan.target.bearing_deg*Math.PI/180;const d=Math.min(2.8,s.plan.target.distance_m);c.strokeStyle='#e6c56a';c.setLineDash([8,6]);c.lineWidth=2;c.beginPath();c.moveTo(ox,oy);c.lineTo(...xy(d*Math.sin(a),d*Math.cos(a)));c.stroke();c.setLineDash([])}
 if(s.plan.goal){const g=s.plan.goal;const [x,y]=xy(g.x_m,g.y_m);c.strokeStyle='#a6e3f0';c.lineWidth=2;c.beginPath();c.arc(x,y,7,0,2*Math.PI);c.stroke();c.fillStyle='#d2f6ff';c.font='12px system-ui';c.fillText('ARRIVÉE · '+fmt(g.distance_to_person_m)+' m de la personne',Math.min(w-230,Math.max(8,x+12)),Math.max(20,y-10))}
 if(s.plan.chosen){c.strokeStyle='#b6ee8d';c.lineWidth=5;c.beginPath();c.moveTo(ox,oy);for(const [x,y]of s.plan.chosen.path)c.lineTo(...xy(x,y));c.stroke()}
 const candidates=(s.plan.candidates||[]).filter(p=>!p.segments),valid=candidates.filter(p=>p.allowed&&Number.isFinite(p.score));const low=Math.min(...valid.map(p=>p.score)),high=Math.max(...valid.map(p=>p.score));
 for(const [index,p]of candidates.entries()){const endpoint=p.path?.at(-1);let a=Number.isFinite(p.direction_deg)?p.direction_deg*Math.PI/180:endpoint?Math.atan2(endpoint[0],endpoint[1]):p.steering_deg*Math.PI/180;if(p.reverse&&!endpoint)a+=Math.PI;if(p.reverse&&endpoint)a=Math.atan2(endpoint[0],endpoint[1]);const color=p.allowed?'hsl('+Math.round(120*(high===low?1:(p.score-low)/(high-low)))+' 75% 65%)':'#82908b';const radius=index%2?260:220;const x=ox+Math.sin(a)*radius,y=oy-Math.cos(a)*radius;if(y<15||y>h-15)continue;c.strokeStyle=color;c.lineWidth=3;c.beginPath();c.moveTo(ox+Math.sin(a)*(radius-16),oy-Math.cos(a)*(radius-16));c.lineTo(x,y);c.stroke();c.font='bold 11px system-ui';c.textAlign='center';c.fillStyle='#10261f';c.fillRect(x-16,y-8,32,16);c.fillStyle=color;c.fillText(Number.isFinite(p.score)?Math.round(p.score):'×',x,y+4)}c.textAlign='start';
 c.strokeStyle='#b5cdac';c.setLineDash([3,5]);c.beginPath();c.arc(ox,oy,(s.plan.footprint_radius_m||.28)*scale,0,Math.PI*2);c.stroke();c.setLineDash([]);c.fillStyle='#e1e9dc';c.fillRect(ox-s.config.width_m*scale/2,oy-s.config.length_m*scale/2,s.config.width_m*scale,s.config.length_m*scale);c.fillStyle='#326449';c.fillRect(ox-3,oy-11,6,9);c.fillStyle='#afc6b5';c.font='12px system-ui';c.fillText('AVANT',ox-20,24);c.fillText('ARRIÈRE',ox-24,h-16);
}
